### ISSUE TITLE
support to use different host compiler for CUDA

### ISSUE THREAD

**Issue by pchong90** [LLNL/Umpire#16]
I'm compiling my code using gcc8 and CUDA9.  But CUDA9 does not support gcc 6 and later. So I used gcc5 as CUDA host compiler. The cmake configuation look like this
```
cmake \
  -DCUDA_NVCC_FLAGS="-ccbin;/path/to/gcc5/bin;--std;c++11" \
  -DCMAKE_INSTALL_PREFIX=/path/to/install/Umpire \
  -DENABLE_OPENMP=OFF \
  -DENABLE_TESTS=OFF \
  -DENABLE_ASSERTS=ON \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  /path/to/source/Umpire
```
The Umpire cmake script failed when testing CUDA compiler, because it is not able to pick the correct host compiler (which is gcc5) in this case.
The issue seems to be in blt. https://github.com/LLNL/blt/blob/master/cmake/thirdparty/SetupCUDA.cmake#L48
It uses `enable_language(cuda)`, which seems to not pick the correct host compiler. 
I workaround this by removing this line.
Any idea how to fix this easily? I would like to have my program build Umpire automaticaly instead of manual hack and build.

**Comment by davidbeckingsale** [comment]
I believe that the correct thing to do would be to specify `-DCMAKE_CXX_COMPILER=/path/to/gcc5/bin`. CMake should then correctly set the host compiler.

What version of CMake are you using?

**Comment by davidbeckingsale** [comment]
If you set `CMAKE_CXX_COMPILER` to be the g++ 5 executable, does it work?

**Comment by pchong90** [comment]
Hi David,
set `CMAKE_CXX_COMPILER` to g++5 does not help.
set `CMAKE_CUDA_HOST_COMPILER` to g++5 fixed the issue.
I think it is CMake's issue by not picking up `CUDA_NVCC_FLAGS` in the `enable_language(cuda)` function. 
I will close this issue, thank you for you help!

**Comment by davidbeckingsale** [comment]
I overlooked this the first time, but the flag variable for CUDA flags changed - it's now `CMAKE_CUDA_FLAGS`. Maybe that would be another fix.
