### ISSUE TITLE
Error -DENABLE_NUMA=On

### ISSUE THREAD

**Issue by andresrubiop** [LLNL/Umpire#170]
**Describe the bug**

Hello I am trying to install Umpire with Numa Option but I am receiving the error below. If i do it without that option it Works! Do you have an idea? 

**To Reproduce**

cmake .. -DCMAKE_INSTALL_PREFIX=/home/arubio/Umpire -DENABLE_CUDA=On -DENABLE_NUMA=On -DENABLE_STATISTICS=Off -DENABLE_GMOCK=On -DENABLE_TESTS=Off -DENABLE_OPENMP=On -DENABLE_WARNINGS_AS_ERRORS=On -DENABLE_C=On -DENABLE_BENCHMARKS=On -DENABLE_TOOLS=On 

make
**Error**
.
.
.
[ 13%] Building CXX object src/umpire/strategy/CMakeFiles/umpire_strategy.dir/MonotonicAllocationStrategy.cpp.o
[ 13%] Building CXX object src/umpire/strategy/CMakeFiles/umpire_strategy.dir/SlotPool.cpp.o
[ 14%] Building CXX object src/umpire/strategy/CMakeFiles/umpire_strategy.dir/SizeLimiter.cpp.o
[ 14%] Building CXX object src/umpire/strategy/CMakeFiles/umpire_strategy.dir/ThreadSafeAllocator.cpp.o
[ 15%] Building CXX object src/umpire/strategy/CMakeFiles/umpire_strategy.dir/NumaPolicy.cpp.o
In file included from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.cpp:7:0:
/home/arubio/Umpire/src/umpire/strategy/NumaPolicy.hpp:40:10: erreur: conflicting return type specified for ‘virtual long int umpire::strategy::NumaPolicy::getCurrentSize() const’
     long getCurrentSize() const noexcept;
          ^
In file included from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.hpp:12:0,
                 from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.cpp:7:
/home/arubio/Umpire/src/umpire/strategy/AllocationStrategy.hpp:69:25: erreur:   overriding ‘virtual std::size_t umpire::strategy::AllocationStrategy::getCurrentSize() const’
     virtual std::size_t getCurrentSize() const noexcept = 0;
                         ^
In file included from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.cpp:7:0:
/home/arubio/Umpire/src/umpire/strategy/NumaPolicy.hpp:41:10: erreur: conflicting return type specified for ‘virtual long int umpire::strategy::NumaPolicy::getHighWatermark() const’
     long getHighWatermark() const noexcept;
          ^
In file included from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.hpp:12:0,
                 from /home/arubio/Umpire/src/umpire/strategy/NumaPolicy.cpp:7:
/home/arubio/Umpire/src/umpire/strategy/AllocationStrategy.hpp:77:25: erreur:   overriding ‘virtual std::size_t umpire::strategy::AllocationStrategy::getHighWatermark() const’
     virtual std::size_t getHighWatermark() const noexcept = 0;
                         ^
make[2]: *** [src/umpire/strategy/CMakeFiles/umpire_strategy.dir/NumaPolicy.cpp.o] Erreur 1
make[1]: *** [src/umpire/strategy/CMakeFiles/umpire_strategy.dir/all] Erreur 2
make: *** [all] Erreur 2

**Comment by jdahm** [comment]
Thank you for bringing this to our attention! Our CI testing framework does not current test builds with with ENABLE_NUMA=ON. We recently made a switch in interface, and these function signatures are out of date.

**Comment by davidbeckingsale** [comment]
Please see #171 - let us know if that works for you @andresrubiop

**Comment by andresrubiop** [comment]
Oh Great! it works.
Thanks

**Comment by davidbeckingsale** [comment]
Awesome! Please let us know if you have any other issues or questions.
