### ISSUE TITLE
More flexibility in configuring cxxopts

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/Umpire#254]
**Is your feature request related to a problem? Please describe.**

The ``cxxopts`` submodule is a required dependency for building umpire, but appears to only be necessary for building ``umpire``'s tests, examples and tools.

**Describe the solution you'd like**

Ideally, 
1. Umpire could be configured to not require ``cxxopts`` when its dependant targets (e.g. tools, examples, tests) are disabled.
2. One could pass in a path to an external ``cxxopts`` in a similar manner to how an external blt is passed in.

**Alternatives ideas**
Since ``cxxopts`` is relatively small, perhaps it could be built it.

**Additional context**

I'm working on a project that does not allow submodules and having a ``cxxopts`` submodule appears to currently be mandatory.

**Comment by davidbeckingsale** [comment]
Hey @kennyweiss - thanks for opening this issue. I can see the problem, and will implement the solution you are proposing.

**Comment by davidbeckingsale** [comment]
We decided to just bundle cxxopts - thanks for the suggestion @kennyweiss.

Closed by #257

**Comment by kennyweiss** [comment]
Thanks @davidbeckingsale !
