### ISSUE TITLE
Prefetching for CUDA Managed Memory

### ISSUE THREAD

**Issue by mrnorman** [LLNL/Umpire#262]
**Is your feature request related to a problem? Please describe.**

I'm wanting to use Umpire with a UM pool to help our Fortran directives code simplify data statements (as in we wouldn't need them anymore). We need the pool to rid the costs of many `cudaMallocManaged` calls as well. However, I looked at the allocate, and it appears not to prefetch. I did a test with a simple stack-based pool linked to Fortran with `iso_c_binding`, and with only `cudaMallocManaged`, each kernel that touches new data has a large latency associated with allocating the data last-minute on the GPU upon first touch.

I was hoping the entire pool would be pulled over upon first touch, but in the Fortran context, it appears to do it individually for each variable. 

**Describe the solution you'd like**

If I add the following to my simple stack pool, it gets rid of the latency for each of the kernels touching new data and significantly improves performance:

```C++
cudaMallocManaged( &pool_ptr , pool_bytes);
cudaMemPrefetchAsync( pool_ptr , pool_bytes , 0 );
cudaDeviceSynchronize();
```

**Sample Code**

```Fortran
program test
  use gator_mod
  implicit none
  integer, parameter :: n = 32*1024
  integer(8), pointer :: a(:), b(:), c(:), d(:)
  integer :: i

  call gator_init(n*4*8)

  call gator_allocate(a,[n])
  call gator_allocate(b,[n])
  call gator_allocate(c,[n])
  call gator_allocate(d,[n])

  !$acc parallel loop default(present)
  do i=1,n
    a(i) = i
  enddo

  !$acc parallel loop default(present)
  do i=1,n
    b(i) = 2*i
  enddo

  !$acc parallel loop default(present)
  do i=1,n
    c(i) = 3*i
  enddo

  !$acc parallel loop default(present)
  do i=1,n
    d(i) = a(i) + b(i) + c(i)
  enddo

  write(*,*) sum(d)

  call gator_deallocate(d)
  call gator_deallocate(c)
  call gator_deallocate(b)
  call gator_deallocate(a)

  call gator_finalize()

end program test
```

**Nvidia Visual Profiler without prefetching**

![Screenshot from 2019-10-10 09-37-48](https://user-images.githubusercontent.com/8059376/66576054-06bf9380-eb45-11e9-9841-52bf5ba82de6.png)

**Nvidia Visual Profiler with prefetching**

![Screenshot from 2019-10-10 10-00-59](https://user-images.githubusercontent.com/8059376/66576086-14751900-eb45-11e9-885a-2c5a0b2f6568.png)

Thanks for considering adding this feature to the UM pool allocator.

**Comment by mcfadden8** [comment]
Does the following provide the functionality you are looking for?

```
auto& rm = ResourceManager::getInstance();
ptr = alloc.allocate(nbytes);
rm.memset(ptr, 0);
```

**Comment by mrnorman** [comment]
Thanks for the response. So `rm.memset` calls `cudaMemSet()` under the hood? I'll give `cudaMemSet()` a try. I recognize calling `cudaMemPrefetchAsync()` might be problematic because it requires knowing what GPU number to do it on, for instance.

**Comment by mrnorman** [comment]
Thanks! Also, is there a simple tutorial of a workflow for using the Fortran bindings for a pool allocator? Sorry if I missed it on the documentation github.io page. I'll keep looking through the code. Unfortunately, my time is a bit divided at the moment, so context switching to Umpire is taking some time for me.

**Comment by davidbeckingsale** [comment]
We have a brief example in our "cookbook" here: https://umpire.readthedocs.io/en/develop/cookbook/pinned_pool.html

**Comment by davidbeckingsale** [comment]
Hey @mrnorman - I've updated #263 with the Fortran bindings and an [example](https://github.com/LLNL/Umpire/blob/feature/prefetch/examples/cookbook/recipe_prefetch_pool.F). Can you take it for a spin and let me know if it works for your use case?

**Comment by mrnorman** [comment]
Sweet, I'll test it out. Thanks.

**Comment by mrnorman** [comment]
Just got done compiling with:

```cmake
cmake -DCMAKE_INSTALL_PREFIX=/home/imn/umpire -DENABLE_FORTRAN=on \
-DENABLE_CUDA=on -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda ..
```

It looks like when I `make install`, the fortran module files aren't propagated over to the include directory:

```bash
[imn@thatchroof:~/umpire] 8-) find . -iname "*.mod"
[imn@thatchroof:~/umpire] 8-) cd ../Umpire/
[imn@thatchroof:~/Umpire] 8-) find . -iname "*.mod"
./build/lib/fortran/fruit_util.mod
./build/lib/fortran/fruit_smoke.mod
./build/lib/fortran/umpire_fortran_generated_tests.mod
./build/lib/fortran/fruit.mod
./build/lib/fortran/umpire_mod.mod
./build/lib/fortran/umpire_fortran_op_tests.mod
[imn@thatchroof:~/Umpire] 8-) 
```

**Comment by davidbeckingsale** [comment]
Doh 🤦‍♂ fixing...

**Comment by davidbeckingsale** [comment]
@mrnorman - updated branch to install modules to `./include/umpire`.

Please let me know if there is a better place to be installing them.

**Comment by davidbeckingsale** [comment]
Awesome, thanks for your patience!

**Comment by davidbeckingsale** [comment]
@mrnorman - do you think it's best if Umpire, or the user handles synchronization? Right now, I have the prefetch operation sync after every call - this is a bit heavy-handed, and it might be best to rip this out and have the user sync as appropriate.

Let me know what you think.

**Comment by evaleev** [comment]
@davidbeckingsale my 2 cents: yes, I tried using this API and the sync was the showstopper. Synchronizing version perhaps should be a separate op, but then the question is what type of synchronization the user need (per stream, per device) ...

**Comment by davidbeckingsale** [comment]
@evaleev - I agree, I think right now we have to let the user decide. We are working on providing portable access to this kind of capability, but it's under development right now.

**Comment by davidbeckingsale** [comment]
#263 added support for this, so I'm going to close this issue. @mrnorman - please open a new issue if you run into any other problems.
