### ISSUE TITLE
Allow for a user to flush memory pools

### ISSUE THREAD

**Issue by mcfadden8** [LLNL/Umpire#28]
Allow for applications to perform a "soft" reset on memory pool strategies that allow it by adding a new API: ResourceManager::flush(Allocator).

**Comment by mcfadden8** [comment]
Great!

I was going to try and work on it tonight, but if you can get to it that would be great.

Thanks,

Sent from my iPad

On Dec 6, 2018, at 5:24 AM, David Beckingsale <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcfadden8<https://github.com/mcfadden8> - I have some time to tackle this today!

**Comment by davidbeckingsale** [comment]
No problem, PR here #29 !
