### ISSUE TITLE
Cannot compile Umpire without git

### ISSUE THREAD

**Issue by TotoGaz** [LLNL/Umpire#282]
I cannot compile Umpire on an environment without `git` (which may happen for CI/CD containers).
I get:
```
CMake Error at src/tpl/umpire/CMakeLists.txt:96 (blt_git_hashcode):
  Unknown CMake command "blt_git_hashcode".
```

**Comment by TotoGaz** [comment]
Hi @mcfadden8! I let you close the issue when it's merged :)

**Comment by mcfadden8** [comment]
Will do.  Just waiting for builds to finish

**Comment by mcfadden8** [comment]
Merged into develop.  Thanks!

**Comment by TotoGaz** [comment]
You're welcome.
Thank you for being reactive.
