### ISSUE TITLE
support for SYCL

### ISSUE THREAD

**Issue by evaleev** [LLNL/Umpire#317]
**Is your feature request related to a problem? Please describe.**

Need to be able to execute on Intel GPUs

**Describe the solution you'd like**

introduce support for SYCL allocations

**Describe alternatives you've considered**

We are dependent on Umpire, and would like to avoid the need to find alternatives, if possible :)

**Additional context**

N/A

**Comment by davidbeckingsale** [comment]
Tracking this internally, will ping you when we have a branch ready for testing!

**Comment by davidbeckingsale** [comment]
@evaleev this support was added with PR #320 🎉
