### ISSUE TITLE
Apply Memory Advice to a Pool, host vs device

### ISSUE THREAD

**Issue by chris-schroeder** [LLNL/Umpire#343]
I'm not sure, but it looks like there's a significant glitch in this page in the Cookbook: https://umpire.readthedocs.io/en/develop/cookbook/pool_advice.html#apply-memory-advice-to-a-pool. The comments say the preferred location is being set to the device/GPU, but the code uses preferred_location_host.

**Comment by davidbeckingsale** [comment]
Ooops you're quite right. The `preferred_location_host` is just the name given to the Allocator. It is actually setting preferred location to the GPU. See [here](https://github.com/LLNL/Umpire/blob/develop/src/umpire/strategy/AllocationAdvisor.cpp#L36) where the `accessing_allocator` parameter is used to determine the location when applying advice.
