### ISSUE TITLE
Version of BLT fails to compile with gcc 9.3

### ISSUE THREAD

**Issue by mclarsen** [LLNL/Umpire#346]
**Describe the bug**

gtest via BLT does not compile with gcc 9.3 (fixed in current blt). Consider updating blt or adding an option to not compile gtest.

**To Reproduce**

compile with gcc 9.3

**Comment by davidbeckingsale** [comment]
Hey @mclarsen - thanks for reporting this. Updating BLT is on our todo list.

If you use the CMake option `-DENABLE_TESTS=Off`, then gtest won't be built (and neither will any tests)

**Comment by mclarsen** [comment]
Thanks David. Is there a `~tests` variant inside the spack package?

**Comment by davidbeckingsale** [comment]
I don't think so :(

**Comment by mclarsen** [comment]
Do the tests get installed? If not, it may be a good idea to never build them in spack. I have been meaning to do this for a while in the libraries I maintain, but haven't gotten to it.

**Comment by davidbeckingsale** [comment]
@mclarsen - which BLT version was this fixed in?

**Comment by davidbeckingsale** [comment]
Since this is fixed in BLT v0.3.0 which is used in Umpire develop I'm going to close this.
