### ISSUE TITLE
Place C++ standard requirements in build system

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/Umpire#352]
**Is your feature request related to a problem? Please describe.**

Umpire specifies either `-std=c++11` or `-std=c++17` for intel compilers in host-config files.

**Describe the solution you'd like**

In CMake, it is possible to specify compiler requirements (CMake compile features). Specifying the exact C++ features required in Umpire, CMake will adapt the flags to provide the minimum required standard coverage.

I think this is better that way since it prevents from having these flags (required ?) in host-config files.

**Describe alternatives you've considered**

BLT also provides a way to set C++ standard requirement. I think CMake method will work well for Umpire.

**Additional context**

This issue arrives now because I am tracking compilers specific requirement to reduce them to the minimum and integrate them to Umpire Spack package. (Related to host-config file generation).

**Comment by davidbeckingsale** [comment]
I believe this is now handled via `BLT_CXX_STD` and `CMAKE_CUDA_STANDARD`
