### ISSUE TITLE
Documentation of resource registration

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/Umpire#354]
**Is your feature request related to a problem? Please describe.**

Insufficient documentation or possible error with registering an allocation with umpire.

**Describe the solution you'd like**

A small working example of an allocator registering a host pointer as a resource in the documentation.

**Describe alternatives you've considered**

We are currently copying data from a natively allocated host array into an umpire-allocated array before moving to the device. We would much rather register the pointer and avoid those extra copies.

```cpp
auto& resmgr = umpire::ResourceManager::getInstance();
auto hostallocator = resmgr.getAllocator("HOST");
auto devallocator = resmgr.getAllocator("DEVICE");

std::size_t size = N * sizeof(double);
auto host_ptr = static_cast<double*>(hostallocator.allocate(size));
auto dev_ptr = static_cast<double*>(devallocator.allocate(size));

// what we are doing:
// we get `double* source` from elsewhere...
std::memcpy(host_ptr, source, size);
resmgr.copy(dev_ptr, host_ptr);

// what we would like to do:
umpire::strategy::AllocationStrategy* strategy = hostallocator.getAllocationStrategy();
umpire::util::AllocationRecord record{source, size, strategy};
resmgr.registerAllocation(source, record);
resmgr.copy(dev_ptr, source);
```
I have attempted the above based on umpire's source, but the data is not copied to the device.
How should we be registering resources?

**Comment by davidbeckingsale** [comment]
Hey @ashermancinelli - I tried your example (from the "what we would like to do") section and it worked just fine. Can you confirm that the data is not being copied when you try this?

**Comment by ashermancinelli** [comment]
It seems you are right... I'm not sure why my assertions were being thrown earlier. If I run into that problem again I'll make sure to raise it here. Would it be helpful if we wrote an example use case in a PR against this repository? Secondarily will we incur a memory leak if we do not deregister the pointer with the resource manager?

Thank you again for your responsiveness, we've been able to make much progress with your help.

**Comment by davidbeckingsale** [comment]
If you would like to turn your use case into an example, that would be fantastic and we would welcome the PR.

If you don't deregister the allocation, you won't leak memory due to the `AllocationRecord`.  Remember that Umpire doesn't automatically deallocate, so you must still deallocate the memory somewhere.

**Comment by ashermancinelli** [comment]
I have the example ready for PR, just waiting on our legal team for clearance.
