### ISSUE TITLE
Hostconfig and Spack package: Where should we draw the line

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/Umpire#367]
### The context

In the Spack package, we can change a lot of parameters to configure the build.
All these parameters are not transposed to the host-config file because it would make them too specific, and naming them (for example) would be a pain.

Instead, a host-config file aims at configuring the toolchain, and how the projects adapts to it.

In practices:

#### Everything "host-config" goes into the `hostconfig` function:

https://github.com/LLNL/Umpire/blob/7e4f2f3c30fc3470b6f3fa2808b837dee2c47939/scripts/uberenv/packages/umpire/package.py#L119

We find there the flags, the compilers paths, the cuda info, etc.

#### Everything "build-config" goes into the `cmake_args` function:

https://github.com/LLNL/Umpire/blob/7e4f2f3c30fc3470b6f3fa2808b837dee2c47939/scripts/uberenv/packages/umpire/package.py#L255

We find there the languages support, tests mode, openmp option, etc.

### The issue

I wanted to point this out to the team because in order to manually build the project, picking a host config may not be enough, unless one wants to rely on the defaults value of the project (if they are set). Instead, one may have to specify some variables on command line.

Also some parameters may be misplaced:
- "deviceconst" may move from `hostconfig` to `cmake_args`,
- "openmp" may move from `cmake_args` to `hostconfig`. 

### Solution

I would appreciate in someone could review the different parameters and discuss with me if it should be placed in the hostconfig, or specified on command line (typically).

### Takaway

A host-config file does not suffice to reproduce a Spack build, although I may have said it was.

**Comment by davidbeckingsale** [comment]
I would like a build to reproducible entirely from a CMake "host-config". I believe this is what we originally discussed. To make this work we need a low overhead way of generating these files "on demand" via uberenv. If there is a way to cache the spack clone I think that would be fine.

**Comment by adrienbernede** [comment]
I see 2 different points in your answer:
- All information for a build should go in the host-config (including build_type, omp, API support).
- Need for a cached spack, (especially in CI I guess).

**Comment by davidbeckingsale** [comment]
Yes, that's right. Is this achievable?

**Comment by adrienbernede** [comment]
First point is easy, it’s mostly a "strategic" decision :), I’m almost there (with the hash in the host-config name).
Second point will need a bit more work. I’ll keep you posted.
