### ISSUE TITLE
Question: Wrapping statically allocated memory (C interface)

### ISSUE THREAD

**Issue by clementFoyer** [LLNL/Umpire#388]
**Is your feature request related to a problem? Please describe.**

I would like to know if there would be a way to wrap memory statically allocated, or allocated from another library, in order to have access to it for copy operations as an example.

**Describe the solution you'd like**

Proposing an API requesting the pointer and the right allocator (or memory resource), either the object, the id or the string name, so the memory can be added to the internal hashtable and the operation like copy are available. It may require to restrict/forbid operations like reallocation, move, and deallocate, as the reference is not owned by the library, but it could be useful. Another option is to provide and API to create our own AllocationRecord.

**Describe alternatives you've considered**

I haven't checked yet if a function is available. I think it is in C++, but maybe not in C? I can always do the wrapping between C and C++ myself and then access the functions from the resource manager.

**Comment by davidbeckingsale** [comment]
Hi @clementFoyer - you can manually register an allocation such that it works with the operations. This requires creating an `AllocationRecord` and then calling the `ResourceManager::registerAllocation` method: https://github.com/LLNL/Umpire/blob/develop/src/umpire/ResourceManager.hpp#L140

We do not expose this in C, primarily due to the `AllocationRecord` containing types that are not accessible in the C interface.

If wrapping it yourself is a problem, please let us know and we can look into adding it to the C API properly.

**Comment by clementFoyer** [comment]
Once I've got my allocator (at least its name), is getting the strategy as simple as calling `ResourceManager::getAllocationStrategy` with the right string, or can I use directly a reference to the allocator as a valid entry as a strategy if I already have a pointer to it?

**Comment by davidbeckingsale** [comment]
You need to get the `AllocationStrategy` pointer, you can get this directly from an `Allocator` by calling `Allocator::getAllocationStrategy`. The `ResourceManager::getAllocationStrategy` method is private.

**Comment by clementFoyer** [comment]
So a small wrapper to pick up the strategy and generate the record would be enough (or just register it directly in a C++ component). Do I need to unregister this record before deallocating the corresponding entry?

**Comment by davidbeckingsale** [comment]
Yes, you must manually deregister the pointer using the `ResourceManager::deregisterAllocation` method. The returned `AllocationRecord` can be ignored.

**Comment by clementFoyer** [comment]
Perfect. Cheers.

**Comment by clementFoyer** [comment]
In case anyone needs to do the same, I leave the code as a comment (it should be a good base). It has not been tested and may break.

```
#include <cstdlib>

#include <umpire/interface/umpire.h>
#include <umpire/Allocator.hpp>
#include <umpire/ResourceManager.hpp>

void umpire_resourcemanager_register_ptr(umpire_resourcemanager *rm,
                                         void *ptr, std::size_t size,
                                         umpire_allocator *allocator)
{
  /* Get Allocation Strategy */
  umpire::Allocator *Alloc_this =
    static_cast<umpire::Allocator *>(allocator->addr);
  umpire::strategy::AllocationStrategy *strat = Alloc_this->getAllocationStrategy();
  /* Register allocation */
  umpire::ResourceManager *RM_this =
    static_cast<umpire::ResourceManager *>(rm->addr);
  RM_this->registerAllocation(ptr, {ptr, size, strat});
}

void mmb_umpire_resourcemanager_deregister_ptr(umpire_resourcemanager *rm,
                                               void *ptr)
{
  /* Deregister allocation */
  umpire::ResourceManager *RM_this =
    static_cast<umpire::ResourceManager *>(rm->addr);
  RM_this->deregisterAllocation(ptr);
}
```

And the following can be export in the C source:
```
/**
 * @brief Register a memory pointer to Umpire so an operation can be executed
 *        on it.
 *
 * @param [inout]   rm The resource manager, as wrapped by the Umpire library.
 * @param [in]      ptr The pointer to be registered.
 * @param [in]      size The size of the memory segment to be registered.
 * @param [in]      allocator The allocator corresponding to the memory layer,
 *                            as wrapped by the Umpire library.
 */
extern void
umpire_resourcemanager_register_ptr(umpire_resourcemanager *rm,
                                    void *ptr, size_t size,
                                    umpire_allocator *allocator);

/**
 * @brief Deregister a memory pointer from Umpire.
 *
 * @param [inout]   rm The resource manager, as wrapped by the Umpire library.
 * @param [in]      ptr The registered pointer.
 */
extern void
umpire_resourcemanager_deregister_ptr(umpire_resourcemanager *rm, void *ptr);
```

**Comment by davidbeckingsale** [comment]
Thanks for the code! 👍

**Comment by clementFoyer** [comment]
Actually, maybe using `umpire::Strategy::mixins::Inspector::registerAllocation()` would be a better way to do it.

**Comment by davidbeckingsale** [comment]
The mixin is designed to be a privately inherited class, as it tracks some other stuff too. Your proposed solution looks exactly like what I would have designed 😄 

We will add this to the C API in future.
