### ISSUE TITLE
Minor fixes / missing code blocks in the tutorial

### ISSUE THREAD

**Issue by pramodk** [LLNL/Umpire#429]
I am going thought [Umpire tutorial](https://umpire.readthedocs.io/en/develop/) and see following and I think there some missing code fragments : 

* [here](https://umpire.readthedocs.io/en/develop/tutorial/dynamic_pool.html) I see below line : is there supposed to be allocation call for `*data`?

> ![image](https://user-images.githubusercontent.com/666852/92312083-e484fe80-efbd-11ea-811f-16f02912db3e.png)

* [here](https://umpire.readthedocs.io/en/develop/tutorial/introspection.html) I see empty code block:

> ![image](https://user-images.githubusercontent.com/666852/92312095-f8306500-efbd-11ea-9949-66c5ca60e73d.png)

* same [here](https://umpire.readthedocs.io/en/develop/cookbook/file_allocation.html) ?

> ![image](https://user-images.githubusercontent.com/666852/92312455-016f0100-efc1-11ea-8aa6-5eaee4d519e0.png)

* same [here](https://umpire.readthedocs.io/en/develop/cookbook/dynamic_pool_heuristics.html) ?

>  ![image](https://user-images.githubusercontent.com/666852/92312514-865a1a80-efc1-11ea-8dc5-bcf32289bbec.png)

Thanks for vert useful library and nice tutorial!

**Comment by davidbeckingsale** [comment]
Hey @pramodk - thanks for reporting this. I think some things got moved around when we applied an auto-formatter to our codebase! We will get this fixed up.

**Comment by pramodk** [comment]
thanks @mcfadden8  fixing this in #479!
