### ISSUE TITLE
Minor tweak to src/umpire/util/memory_sanitizers.hpp

### ISSUE THREAD

**Issue by mcordery** [LLNL/Umpire#433]
When compiling Umpire with our newest compiler (based on clang) I ran across a particular problem in src/umpire/util/memory_sanitizers.hpp. Basically, the problem occurs here:

 #if (defined(__clang__) && !defined(__ibmxl__)) || \
     (defined(__GNUC__) && __GNUC__ > 4)
#if ( !defined(__SYCL_COMPILER_VERSION) )
#include <sanitizer/asan_interface.h>
#endif

In our particular version, the include file doesn't exist, perhaps because it's in development but there may be reasons it's not. In any event, I worked around this by the following

 #if defined __has_include
 #if __has_include(<sanitizer/asan_interface.h>)
 #include <sanitizer/asan_interface.h>
 #endif
 #endif

This should work for gcc as well as clang and clang based compilers. Don't know about xl though last I knew there was talk afoot of moving XL to clang. If this has a side effect, please let me know.

**Comment by mcfadden8** [comment]
Thanks @mcordery, I will try and take a look at this later this week.

Marty

**Comment by mcordery** [comment]
I do note that if I test with icc/icpc, then everything runs fine. If I run the tests with icpx (clang based) the following tests fails.
icpc - all 26 tests passed
icpx - five tests failed
The following tests FAILED:
         17 - allocator_integration_tests (Failed)
         18 - memory_resource_traits_tests (Failed)
         19 - strategy_tests (Child aborted)
         20 - operation_tests (Failed)
         22 - primary_pool_tests (Failed)
I'm a bit curious of the failure of these tests is related to the work around I used above or if I'm missing something.

**Comment by mcfadden8** [comment]
Thank you Matthew,

If you could please submit this as a separate problem ticket and provide the details for how Umpire was configured to use icpx as well as the icpx version used, we may be able to review as a separate issue.

Marty

On Sep 14, 2020, at 1:55 PM, Matthew Cordery <notifications@github.com<mailto:notifications@github.com>> wrote:



I do note that if I test with icc/icpc, then everything runs fine. If I run the tests with icpx (clang based) the following tests fails.
icpc - all 26 tests passed
icpx - five tests failed
The following tests FAILED:
17 - allocator_integration_tests (Failed)
18 - memory_resource_traits_tests (Failed)
19 - strategy_tests (Child aborted)
20 - operation_tests (Failed)
22 - primary_pool_tests (Failed)
I'm a bit curious of the failure of these tests is related to the work around I used above or if I'm missing something.

**Comment by mcfadden8** [comment]
This was fixed in the pull request above.
