### ISSUE TITLE
Sanitizer tests controlled with a cmake option that was removed

### ISSUE THREAD

**Issue by adayton1** [LLNL/Umpire#527]
**Describe the bug**

https://github.com/LLNL/Umpire/blob/b18d8e59d72aa336999dd91febe5528533775258/tests/tools/CMakeLists.txt#L8

The ENABLE_SANITIZERS CMake option was removed at some point in favor of automatically detecting address sanitizer support, which appears to set the UMPIRE_HAS_ASAN CMake variable. I believe that should be used here instead of ENABLE_SANITIZERS.

**Comment by davidbeckingsale** [comment]
Good catch, thanks @adayton1
