### ISSUE TITLE
Consider using tagged commits of submodules when releasing new versions

### ISSUE THREAD

**Issue by haampie** [LLNL/Umpire#530]
**Is your feature request related to a problem? Please describe.**

In Spack it is preferrable to use tarballs over cloning git repo's with submodules, since that way we can add checksums to verify integrity of the sources. I tried to set that up for Umpire, but couldn't,  because there's only a single release of Umpire where `blt` is on a tagged version. I didn't check `camp`.

**Describe the solution you'd like**

When releasing a new version of Umpire, make sure its dependencies are on tagged versions, so that package managers can actually refer to the dependencies and add checksums for all.

**Comment by davidbeckingsale** [comment]
Spack can handle commits for versions, and since blt and camp have Spack packages I would suggest using those commit hashes to set up the required versions for the dependencies in Umpire, if this is important to you.

Umpire doesn't control the release schedule of those other packages and we often need to update them without a numbered release.

**Comment by haampie** [comment]
I know it's possible to do something like `version('1.0.0-somehash', commit=somehash)` for `blt` and `camp`, but it's not great.

FWIW, currently the spack package is broken for older versions, because it sets

```
options.append("-DBLT_SOURCE_DIR={0}".format(spec['blt'].prefix))
options.append("-Dcamp_DIR={0}".format(spec['camp'].prefix))
```

and does not constrain `camp` and `blt` to a compatible version.

Current best option is to drop these dependencies and handle them through submodules then

**Comment by davidbeckingsale** [comment]
BLT and camp now point at tagged versions (and we are going to be doing a better job of keeping things up to date moving forwards). Latest spack packages enforce the correct version constraints.
