### ISSUE TITLE
HIP Runtime Linker Errors

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/Umpire#538]
**Describe the bug**

Exported CMake targets explicitly link against target `hip_runtime`, although hip_runtime is just a collection of headers and not a concrete library afaik (is hip_runtime an interface/alias cmake target internal to umpire's cmake?).

To circumvent this, I build Umpire and then manually remove `hip_runtime` from array on line 76 of `<prefix>/share/umpire/cmake/umpire-targets.cmake`. From there I'm able to build all of my targets that depend on umpire and hip.

**Expected behavior**

Import Umpire's cmake targets without passing explicit `-lhip_runtime` link library to user's targets.

**Compilers & Libraries (please complete the following information):**

I'll have to ensure hardware on early access machines can be discussed here... @pelesh please advise.

**Additional context**

Installed using spack fwiw.

If I'm simply using the imported cmake targets incorrectly, please let me know. Thank you!

**Comment by davidbeckingsale** [comment]
The `hip_runtime` target comes from BLT. When you build a HIP-enabled Umpire it is required to be linked to the HIP runtime library, which is most easily done by linking with `hipcc`. The target handles this.

How do you support HIP compilation in your application?

**Comment by ashermancinelli** [comment]
Perhaps I'm just misusing the library. According to [this issue in ROCm repo](https://github.com/ROCm-Developer-Tools/HIP/issues/231), we set C++ compiler to hip clang and link against `hip::device` for device code, as discussed on [this ROCm documentation page](https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html). Do you see anything immediately wrong with this, and is there additional documentation for using Umpire with hip?

**Comment by ashermancinelli** [comment]
For additional context: 

* The error occurs in the link step, the sources with RAJA kernels using HIP policies compile fine.
* The final linked targets also link to cmake target hip::device, and are confirmed to use `--hip-link`

**Comment by ashermancinelli** [comment]
We ran into this issue with RAJA - would you like me to raise an issue on that repo as well? After removing the hip_runtime targets manually our entire stack built and ran successfully.

**Comment by davidbeckingsale** [comment]
I'm hopeful that #541 will help - if you would like to try and build and install that branch and see if the issue goes away that would be super helpful. I can than make the same change to RAJA.

**Comment by ashermancinelli** [comment]
The fix has been merged into develop and I have validated the patch myself. Thanks for the help!
