### ISSUE TITLE
Umpire does not find camp after spack build

### ISSUE THREAD

**Issue by mclarsen** [LLNL/Umpire#543]
**Describe the bug**

Umpire does not find camp after spack build. When I try to include umpire in my project, it fails on the camp dir, although umpire itself built fine. Does umpire require camp, and if so, why doesn't it depend on camp inside spack?

**Comment by mclarsen** [comment]
This is what I have to use: https://github.com/LLNL/devil_ray/blob/develop/scripts/uberenv/packages/umpire/package.py

**Comment by davidbeckingsale** [comment]
It does depend on camp in Spack: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/umpire/package.py

**Comment by mclarsen** [comment]
I swear I looked! Thanks David.

**Comment by davidbeckingsale** [comment]
No problem 👍
