### ISSUE TITLE
Error when trying to build with HIP support

### ISSUE THREAD

**Issue by pbauman** [LLNL/Umpire#556]
**Describe the bug**
I encounter the following compilation error:
<pre>
[ 17%] Building CXX object src/umpire/resource/CMakeFiles/umpire_resource.dir/HostResourceFactory.cpp.o
<command-line>: error: macro names must be identifiers
In file included from /home/users/coe0093/work/umpire/Umpire/src/umpire/alloc/MallocAllocator.hpp:16,
                 from /home/users/coe0093/work/umpire/Umpire/src/umpire/resource/HostResourceFactory.cpp:9:
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:387:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^~~~~
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:412:61: error: ‘hipHostMallocDefault’ was not declared in this scope
                                        unsigned int flags = hipHostMallocDefault) {
                                                             ^~~~~~~~~~~~~~~~~~~~
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:412:61: note: suggested alternative: ‘hipComputeModeDefault’
                                        unsigned int flags = hipHostMallocDefault) {
                                                             ^~~~~~~~~~~~~~~~~~~~
                                                             hipComputeModeDefault
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:418:61: error: ‘hipMemAttachGlobal’ was not declared in this scope
                                        unsigned int flags = hipMemAttachGlobal) {
</pre>

**To Reproduce**
I configured using the following:

`cmake -DENABLE_HIP=On -DENABLE_C=On ../Umpire`

**Expected behavior**

I expect to be able to compile and install Umpire with HIP support on machines with AMD GPUs. 

**Compilers & Libraries (please complete the following information):**
 - gcc 8.3.1 (default system compiler
 - ROCm 4.1.1

**Additional context**
Here is the output with `VERBOSE=1`:
<pre>
[ 17%] Building CXX object src/umpire/resource/CMakeFiles/umpire_resource.dir/HostResourceFactory.cpp.o
cd /home/users/coe0093/work/umpire/build/src/umpire/resource && /usr/bin/c++   -I/home/users/coe0093/work/umpire/Umpire/src/umpire/tpl/camp/include -isystem /opt/rocm-4.1.1/hip/include -I/home/users/coe0093/work/umpire/Umpire/src -I/home/users/coe0093/work/umpire/build/include  -Wpedantic       -Wall -Wextra  -fPIC   -D -Wno-unused-parameter -std=c++11 -o CMakeFiles/umpire_resource.dir/HostResourceFactory.cpp.o -c /home/users/coe0093/work/umpire/Umpire/src/umpire/resource/HostResourceFactory.cpp
<command-line>: error: macro names must be identifiers
In file included from /home/users/coe0093/work/umpire/Umpire/src/umpire/alloc/MallocAllocator.hpp:16,
                 from /home/users/coe0093/work/umpire/Umpire/src/umpire/resource/HostResourceFactory.cpp:9:
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:387:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^~~~~
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:412:61: error: ‘hipHostMallocDefault’ was not declared in this scope
                                        unsigned int flags = hipHostMallocDefault) {
                                                             ^~~~~~~~~~~~~~~~~~~~
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:412:61: note: suggested alternative: ‘hipComputeModeDefault’
                                        unsigned int flags = hipHostMallocDefault) {
                                                             ^~~~~~~~~~~~~~~~~~~~
                                                             hipComputeModeDefault
/opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:418:61: error: ‘hipMemAttachGlobal’ was not declared in this scope
                                        unsigned int flags = hipMemAttachGlobal) {
</pre>

So it appears that `-D__HIP_PLATFORM_HCC__` is not being passed to the compilation line. But, I also see that `hipcc` is not being used. So I tried explicitly using `hipcc` for the C++ compiler, but the configure step did not complete successfully:

<pre>
cmake -DCMAKE_CXX_COMPILER=/opt/rocm-4.1.1/bin/hipcc -DENABLE_HIP=On ../Umpire/
-- The CXX compiler identification is Clang 12.0.0
-- The C compiler identification is Clang 12.0.0
-- Check for working CXX compiler: /opt/rocm-4.1.1/bin/hipcc
-- Check for working CXX compiler: /opt/rocm-4.1.1/bin/hipcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Check for working C compiler: /opt/cray/pe/craype/2.7.7.4/bin/cc
-- Check for working C compiler: /opt/cray/pe/craype/2.7.7.4/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using CMake version 3.11.4
-- BLT Version: 0.3.6
-- CMake Version: 3.11.4
-- CMake Executable: /usr/bin/cmake
-- Found Git: /usr/bin/git (found version "2.18.4") 
-- Git Support is ON
-- Git Executable: /usr/bin/git
-- Git Version: 2.18.4
-- MPI Support is OFF
-- OpenMP Support is Off
-- CUDA Support is Off
-- HIP Support is On
-- Found HIP: /opt/rocm-4.1.1/hip (found version "4.1.21114-e9025c25") 
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- HIP version:      4.1.21114-e9025c25
-- HIP platform:     amd
-- HCC Support is OFF
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Sphinx support is ON
-- Failed to locate Sphinx executable (missing: SPHINX_EXECUTABLE) 
-- Valgrind support is ON
-- Found Valgrind: /usr/bin/valgrind  
-- AStyle support is ON
-- Failed to locate AStyle executable (missing: ASTYLE_EXECUTABLE) 
-- ClangFormat support is ON
-- Found ClangFormat: /opt/rocm-4.1.1/llvm/bin/clang-format  
-- Uncrustify support is ON
-- Failed to locate Uncrustify executable (missing: UNCRUSTIFY_EXECUTABLE) 
-- Yapf support is ON
-- Failed to locate Yapf executable (missing: YAPF_EXECUTABLE) 
-- CMakeFormat support is ON
-- Failed to locate CMakeFormat executable (missing: CMAKEFORMAT_EXECUTABLE) 
-- Cppcheck support is ON
-- Failed to locate Cppcheck executable (missing: CPPCHECK_EXECUTABLE) 
-- ClangQuery support is Off
-- ClangTidy support is ON
-- Found ClangTidy: /opt/rocm-4.1.1/llvm/bin/clang-tidy  
-- C Compiler family is Clang
-- Adding optional BLT definitions and compiler flags
-- Setting CMAKE_CXX_EXTENSIONS to Off
-- Standard C++11 selected
-- Enabling all compiler warnings on all targets.
-- Fortran support disabled.
-- CMAKE_C_FLAGS flags are:    -Wall -Wextra 
-- CMAKE_CXX_FLAGS flags are:       -Wall -Wextra 
-- CMAKE_EXE_LINKER_FLAGS flags are:  
-- Google Test Support is ON
-- Google Mock Support is On
-- Found PythonInterp: /usr/bin/python (found version "3.6.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Memcheck suppressions file: /home/users/coe0093/work/umpire/Umpire/cmake/valgrind.supp
-- Setting C standard to 99
-- Checking for std::filesystem
-- Performing Test UMPIRE_ENABLE_FILESYSTEM
-- Performing Test UMPIRE_ENABLE_FILESYSTEM - Failed
-- std::filesystem NOT found, using POSIX
-- Performing Test UMPIRE_HAS_ASAN
-- Performing Test UMPIRE_HAS_ASAN - Success
-- Umpire may be built with ASAN support
-- Configuring done
CMake Error in src/umpire/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 12.0.0.
</pre>

 Please let me know if I can provide other details. Thanks!

**Comment by davidbeckingsale** [comment]
Hey @pbauman - this is an issue that came up with the new ROCm release, and is fixed in BLT here: https://github.com/LLNL/blt/pull/473

If you update the BLT submodule yourself it should build. You do not need to pass `hipcc` as the `CMAKE_CXX_COMPILER`.

I'll create a PR to bump the BLT version in Umpire now...

**Comment by pbauman** [comment]
OK, thanks for the heads-up @davidbeckingsale  and thanks for the quick reply. I'll give this a whirl tomorrow.

**Comment by pbauman** [comment]
Hi @davidbeckingsale, I manually applied the changes that are present in LLNL/blt#473 and that got me a bit farther, but unfortunately, it still looks like there's an issue. It appears that the path to `hsa` is not included in the compilation line:

<pre>
[ 17%] Building CXX object src/umpire/resource/CMakeFiles/umpire_resource.dir/HostResourceFactory.cpp.o
cd /home/users/coe0093/work/umpire/build/src/umpire/resource && /usr/bin/c++   -I/home/users/coe0093/work/umpire/Umpire/src/umpire/tpl/camp/include -isystem /opt/rocm-4.1.1/hip/include -I/home/users/coe0093/work/umpire/Umpire/src -I/home/users/coe0093/work/umpire/build/include  -Wpedantic       -Wall -Wextra  -fPIC   -D__HIP_PLATFORM_HCC__ -Wno-unused-parameter -std=c++11 -o CMakeFiles/umpire_resource.dir/HostResourceFactory.cpp.o -c /home/users/coe0093/work/umpire/Umpire/src/umpire/resource/HostResourceFactory.cpp
In file included from /opt/rocm-4.1.1/hip/include/hip/hip_runtime_api.h:383,
                 from /home/users/coe0093/work/umpire/Umpire/src/umpire/alloc/MallocAllocator.hpp:16,
                 from /home/users/coe0093/work/umpire/Umpire/src/umpire/resource/HostResourceFactory.cpp:9:
/opt/rocm-4.1.1/hip/include/hip/hcc_detail/hip_runtime_api.h:48:10: fatal error: hsa/hsa.h: No such file or directory
 #include <hsa/hsa.h>
          ^~~~~~~~~~~
compilation terminated.
</pre>

I checked both on this system (redwood) and my home box and `/opt/rocm/hip/include` doesn't give any pointers (via symlink or otherwise) to the hsa directory (nominally located in `/opt/rocm/include/hsa`, `/opt/rocm/hsa/include` is a symlink to the former). I also tried back as far as ROCm 3.10 on redwood. Please let me know if I can provide more info, I understand this is a pain.

**Comment by davidbeckingsale** [comment]
Whoops, sorry about this. IIRC this is a bit of a legacy thing from when the symlinks existed - you can manually provide the list of required includes as `-DHIP_RUNTIME_INCLUDE_DIRS=...`  when you run CMake. Example here: https://github.com/LLNL/Umpire/blob/develop/Dockerfile#L69

**Comment by pbauman** [comment]
Apologies for the slow turn-around on my end. That was the trick and your example was very helpful. I was able to build Umpire with HIP successfully and use it in HYPRE. Thanks for the help!

**Comment by davidbeckingsale** [comment]
Great! Thank you for following up.
