### ISSUE TITLE
Can tell me some detail about NumaPolicy? 

### ISSUE THREAD

**Issue by yuanAIhan** [LLNL/Umpire#594]
I want to read the resource code, but I do not understand the the policy of numa. Could you tell me something about it ?

**Comment by davidbeckingsale** [comment]
NumaPolicy allows you to allocate memory that will be placed on a specific numa node in the system. This can be used to ensure memory is "close" to execution resources that will be accessing it. You can see some of the implementation here: https://github.com/LLNL/Umpire/blob/develop/src/umpire/util/numa.cpp#L32-L49

**Comment by yuanAIhan** [comment]
> NumaPolicy allows you to allocate memory that will be placed on a specific numa node in the system. This can be used to ensure memory is "close" to execution resources that will be accessing it. You can see some of the implementation here: https://github.com/LLNL/Umpire/blob/develop/src/umpire/util/numa.cpp#L32-L49

Could I get some examples about the operation of numa ?

**Comment by davidbeckingsale** [comment]
I'm not sure what kind of examples you are looking for. Is there a specific task you are trying to accomplish?
