### ISSUE TITLE
xlc compiler

### ISSUE THREAD

**Issue by jeanlucf22** [LLNL/Umpire#619]
**Describe the bug**

Cannot build with XL compiler on Summit at OLCF. Error message:

In file included from /gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/MixedPool.cpp:8:
In file included from /gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/MixedPool.hpp:10:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/map:62:
/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_multimap.h:130:41: error: 'rebind'
      following the 'template' keyword does not refer to a template
      typedef typename _Alloc::template rebind<value_type>::other
                                        ^~~~~~
/gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/QuickPool.hpp:150:5: note: in instantiation of
      template class 'std::multimap<unsigned long, umpire::strategy::QuickPool::Chunk *, std::less<unsigned long>,
      umpire::strategy::QuickPool::pool_allocator<std::pair<const unsigned long, umpire::strategy::QuickPool::Chunk
      *> > >' requested here
    SizeMap::iterator size_map_it;
    ^
In file included from /gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/MixedPool.cpp:8:
In file included from /gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/MixedPool.hpp:10:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/map:60:
/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_tree.h:335:24: error: type 'int'
      cannot be used prior to '::' because it has no members
      typedef typename _Alloc::template rebind<_Rb_tree_node<_Val> >::other
                       ^
/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_multimap.h:136:17: note: in
      instantiation of template class 'std::_Rb_tree<unsigned long, std::pair<const unsigned long,
      umpire::strategy::QuickPool::Chunk *>, std::_Select1st<std::pair<const unsigned long,
      umpire::strategy::QuickPool::Chunk *> >, std::less<unsigned long>, int>' requested here
      _Rep_type _M_t;
                ^
/gpfs/alpine/mat190/scratch/jeanluc/GIT/Umpire/src/umpire/strategy/QuickPool.hpp:150:5: note: in instantiation of
      template class 'std::multimap<unsigned long, umpire::strategy::QuickPool::Chunk *, std::less<unsigned long>,
      umpire::strategy::QuickPool::pool_allocator<std::pair<const unsigned long, umpire::strategy::QuickPool::Chunk
      *> > >' requested here
    SizeMap::iterator size_map_it;
    ^

**To Reproduce**

(using modules loaded by default)
module load cmake
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=xlc++ ..
make

**Expected behavior**

Complete build

**Compilers & Libraries (please complete the following information):**
 - Compiler & version: xl/16.1.1-5
 - CUDA version (if applicable): 

**Additional context**

Was able to build successfully with gnu compiler

**Comment by davidbeckingsale** [comment]
Closing this for now - please reopen if you have more problems.
