### ISSUE TITLE
Compiling Umpire 6.0.0 with Clang compiler requires adding #include <stdexcept> to camp/defines.hpp

### ISSUE THREAD

**Issue by victor-anisimov** [LLNL/Umpire#645]
**Describe the bug**

A clear and concise description of what the bug is:
Clang compiler requires adding #include <stdexcept> to camp/defines.hpp

**To Reproduce**

git clone --recursive https://github.com/LLNL/Umpire.git Umpire
cd Umpire
git checkout e6bd629c66109dfa090712df0796d2b5b97552b3
cmake -H. -Bbuild -DENABLE_CUDA=On -DUMPIRE_ENABLE_FILESYSTEM=OFF -DENABLE_TESTS=On -DENABLE_EXAMPLES=On -DCMAKE_CUDA_ARCHITECTURES=70 -DCMAKE_CUDA_HOST_COMPILER=icpx -DCMAKE_CUDA_FLAGS_INIT=-allow-unsupported-compiler -DBLT_CXX_STD=c++17
cd build; export VERBOSE=1; make

**Expected behavior**

A clear and concise description of what you expected to happen:
Compilation ends up with error when compiling file primary_pool_tests.cpp

In file included from /home/vanisimov/tiledarray/Umpire/tests/integration/primary_pool_tests.cpp:11:
In file included from /home/vanisimov/tiledarray/Umpire/src/umpire/tpl/camp/include/camp/camp.hpp:17:
/home/vanisimov/tiledarray/Umpire/src/umpire/tpl/camp/include/camp/defines.hpp:203:16: error: no member named 'runtime_error' in namespace 'std'
    throw std::runtime_error(msg);
          ~~~~~^
1 error generated.

**Compilers & Libraries (please complete the following information):**
 - Compiler & version: Clang 14.0.0
 - CUDA version (if applicable): 11.2.0
 - V100 nVidia GPU

**Additional context**

The latest commit of Umpire, 2775bbec938288792dfb51bdb672d0f7a92e22be does not require adding #include <stdexcept> to camp/defines.hpp. However, after compilation many unit tests `make test` fail.

**Comment by davidbeckingsale** [comment]
This is fixed with a slightly newer camp release - Umpire 6.0.0 should be compatible with camp@0.3.0 (which contains this include)
