### ISSUE TITLE
CUDA compilation on Summit with gcc 10.2 and cuda 11.3

### ISSUE THREAD

**Issue by PaulMullowney** [LLNL/Umpire#667]
What's the correct way to specify the cuda architecture when configuring with cmake. I tried:

-DCMAKE_CUDA_ARCHITECTURES=70

However, the cmake configure fails via:

-- CUDA Support is ON
-- The CUDA compiler identification is NVIDIA 11.3.109
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: /sw/summit/cuda/11.3.1/bin/nvcc
-- Check for working CUDA compiler: /sw/summit/cuda/11.3.1/bin/nvcc - broken
CMake Error at /autofs/nccs-svm1_sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/cmake-3.20.2-hvb6iokb3qczolaj7v63ouqnqsd4ecie/share/cmake-3.20/Modules/CMakeTestCUDACompiler.cmake:52 (message):
  The CUDA compiler

    "/sw/summit/cuda/11.3.1/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /gpfs/alpine/cfd116/scratch/mullowne/Umpire/build_cuda/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_3e6f2/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_3e6f2.dir/build.make CMakeFiles/cmTC_3e6f2.dir/build
    gmake[1]: Entering directory '/gpfs/alpine/cfd116/scratch/mullowne/Umpire/build_cuda/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_3e6f2.dir/main.cu.o
    /sw/summit/cuda/11.3.1/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/sw/summit/gcc/10.2.0-2/bin/g++   -arch sm_  -std=c++11 -MD -MT CMakeFiles/cmTC_3e6f2.dir/main.cu.o -MF CMakeFiles/cmTC_3e6f2.dir/main.cu.o.d -x cu -c /gpfs/alpine/cfd116/scratch/mullowne/Umpire/build_cuda/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_3e6f2.dir/main.cu.o
    nvcc fatal   : Value 'sm_' is not defined for option 'gpu-architecture'
    gmake[1]: *** [CMakeFiles/cmTC_3e6f2.dir/build.make:79: CMakeFiles/cmTC_3e6f2.dir/main.cu.o] Error 1
    gmake[1]: Leaving directory '/gpfs/alpine/cfd116/scratch/mullowne/Umpire/build_cuda/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_3e6f2/fast] Error 2

  CMake will not be able to correctly generate this project.

**Comment by davidbeckingsale** [comment]
I would expect that to work. You could also try adding `-arch sm_70` directly to CMAKE_CUDA_FLAGS.

**Comment by PaulMullowney** [comment]
Ultimately, I was able to get it compile and build with: 

cmake .. -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DENABLE_CUDA=ON -DCMAKE_INSTALL_PREFIX=/gpfs/alpine/cfd116/scratch/mullowne/install/gpu/umpire-$(date +"%Y-%m-%d")/ -DCMAKE_VERBOSE_MAKEFILE=ON -DUMPIRE_ENABLE_C=ON -DCMAKE_CUDA_ARCHITECTURES=70 -DCMAKE_CXX_STANDARD=11

However, I needed to add:
#include < stdexcept >
to:
src/umpire/tpl/campinclude/camp/defines.hpp

My goal is to use Umpire within Hypre. At the end of my Hypre build I see:

Building libHYPRE.so ...
/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-vet2p2ttgtyh6ixvtxq523rdi7ydj7r7/bin/mpicxx -shared  -o libHYPRE-2.23.0.so   /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/IJ_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/distributed_ls/Euclid/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/distributed_ls/ParaSails/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/distributed_ls/pilut/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/distributed_matrix/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/krylov/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/matrix_matrix/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/multivector/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_block_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/seq_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/sstruct_ls/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/sstruct_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/struct_ls/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/struct_mv/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/utilities/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/blas/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/lapack/*.o /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/IJ_mv/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_mv/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/seq_mv/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/sstruct_ls/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/sstruct_mv/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/struct_ls/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/struct_mv/*.obj /gpfs/alpine/cfd116/scratch/mullowne/hypre/src/utilities/*.obj        -lm  -L/sw/summit/cuda/11.3.1//lib64 -lcudart -lnvToolsExt -lcusparse -lcurand      -L/gpfs/alpine/cfd116/scratch/mullowne/install/gpu/umpire-2021-10-07/lib/  -lumpire   -Wl,-soname,libHYPRE-2.23.0.so -Wl,-z,defs
/gpfs/alpine/cfd116/scratch/mullowne/install/gpu/umpire-2021-10-07/lib//libumpire.a(device_allocator_helper.cpp.o): In function `__sti____cudaRegisterAll()':
/tmp/tmpxft_000bad82_00000000-6_device_allocator_helper.cudafe1.stub.c:14: undefined reference to `__cudaRegisterLinkedBinary_58_tmpxft_000bad82_00000000_7_device_allocator_helper_cpp1_ii_aaf1a6d1'
/gpfs/alpine/cfd116/scratch/mullowne/install/gpu/umpire-2021-10-07/lib//libumpire.a(DeviceAllocator.cpp.o): In function `__sti____cudaRegisterAll()':
/tmp/tmpxft_000bad80_00000000-6_DeviceAllocator.cudafe1.stub.c:14: undefined reference to `__cudaRegisterLinkedBinary_50_tmpxft_000bad80_00000000_7_DeviceAllocator_cpp1_ii_53c5c9f9'
/usr/bin/ld: link errors found, deleting executable `libHYPRE-2.23.0.so'
collect2: error: ld returned 1 exit status

Any ideas on how to resolve this?

**Comment by davidbeckingsale** [comment]
I think you need to do a device link before the final hypre link. This should be handled by a CMake-based build system when the umpire targets are imported.

I’m not sure the specifics of the HYPRE build system.

**Comment by PhilipDeegan** [comment]
I had more luck when building/linking UMPIRE with cmake configured with ```-DBUILD_SHARED_LIBS=ON```
