### ISSUE TITLE
Compiler error when enabling CUDA

### ISSUE THREAD

**Issue by pwang234** [LLNL/Umpire#685]
**Describe the bug**

I encountered the following compiler error when trying to compile Umpire:

In file included from /fs/hypre/Umpire/src/umpire/tpl/camp/include/camp/camp.hpp:17,
                 from /fs/hypre/Umpire/tests/integration/test_helpers.hpp:9,
                 from /fs/hypre/Umpire/tests/integration/operation_tests.cpp:7:
/fs/hypre/Umpire/src/umpire/tpl/camp/include/camp/defines.hpp: In function 'cudaError_t camp::cudaAssert(cudaError_t, const char*, const char*, int)':
/fs/hypre/Umpire/src/umpire/tpl/camp/include/camp/defines.hpp:203:16: error: 'runtime_error' is not a member of 'std'

It looks the issue is that "#include <stdexcept>" was missing in defines.hpp.

**To Reproduce**

cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DENABLE_CUDA=On -DENABLE_OPENMP=Off -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CUDA_ARCHITECTURES=70 -DENABLE_C=On ../
make -j8

**Expected behavior**

A clear and concise description of what you expected to happen: compile with no errors

**Compilers & Libraries (please complete the following information):**
 - Compiler & version: [e.g. GCC 4.9.3]:  gcc 11.1.0
 - CUDA version (if applicable): 11.4

**Additional context**

**Comment by davidbeckingsale** [comment]
This is fixed using a newer version of camp.
