### ISSUE TITLE
CMake can't find umpire

### ISSUE THREAD

**Issue by PaulMullowney** [LLNL/Umpire#762]
Hi,
I have the following cmake code for finding umpire:
  set(CMAKE_PREFIX_PATH ${UMPIRE_ROOT_DIR} ${CMAKE_PREFIX_PATH})
  message(STATUS "Looking for Umpire at ${UMPIRE_ROOT_DIR}")
  find_package(umpire REQUIRED CONFIG)
  message(STATUS "Found Umpire = ${UMPIRE_DIR}")
  
I supply UMPIRE_ROOT_DIR during configuration. I see:
-- Looking for Umpire at /gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager-hma/spack/opt/spack/cray-sles15-zen3/clang-14.0.0/umpire-2022.03.1-zysyhnfci37w7ysfoifpei4bfyasunv5
-- Found Umpire =

If I look in UMPIRE_ROOT_DIR, I see:
[mullowne@login2.crusher hypre-mini-app]$ ls /gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager-hma/spack/opt/spack/cray-sles15-zen3/clang-14.0.0/umpire-2022.03.1-zysyhnfci37w7ysfoifpei4bfyasunv5
bin  include  lib  share

Can you advise on how to find umpire properly with CMake?
Thanks,
-Paul

**Comment by PaulMullowney** [comment]
I see the issue. Nevermind.

**Comment by PaulMullowney** [comment]
find_package(umpire)
keeps finding the cmake package and not the top directory. 
/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager-hma/spack/opt/spack/cray-sles15-zen3/clang-14.0.0/umpire-2022.03.1-zysyhnfci37w7ysfoifpei4bfyasunv5/lib/cmake/umpire


Any ideas on how to fix?

**Comment by davidbeckingsale** [comment]
That's where `umpire-config.cmake` is installed. After running `find_package`, you should be able to just depend on the `umpire` target within your own CMake project.

**Comment by PaulMullowney** [comment]
Understood. But I was expecting umpire_INCLUDE_DIRS, umpire_LIBRARIES to be defined after find_package is called. They're not.
