### ISSUE TITLE
spack build with ROCm 5.1.0 on crusher

### ISSUE THREAD

**Issue by PaulMullowney** [LLNL/Umpire#763]
Not sure how to resolve this. I add +rocm as my spack variant.

CMake Error in CMakeLists.txt:
  Target "blt_hip" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager-hma/stage/spack-stage-umpire-2022.03.1-tqmh5ayb6ho36rsixipec3swpyo6p7y6/spack-src/HIP_CLANG_INCLUDE_PATH-NOTFOUND/.."

  which is prefixed in the source directory.

CMake Error in CMakeLists.txt:
  Target "blt_hip" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager-hma/stage/spack-stage-umpire-2022.03.1-tqmh5ayb6ho36rsixipec3swpyo6p7y6/spack-src/HIP_CLANG_INCLUDE_PATH-NOTFOUND/.."

  which is prefixed in the source directory.

**Comment by davidbeckingsale** [comment]
Hey @PaulMullowney this was a recent breakage that should be addressed by modifying your Umpire spack package as seen in this PR: https://github.com/LLNL/Umpire/pull/767/files#diff-dcd3e921ce7c31781129dbf03081df2346e221003b3dae0c55ceddb33896ad39R204-R208

We will have this up in mainline Spack soon.

**Comment by PaulMullowney** [comment]
Thanks for the update. Right now, I'm just hooking into system versions Umpire on summit and crusher, but being able to build via spack is helpful.
