### ISSUE TITLE
`std::filesystem` incorrectly detected

### ISSUE THREAD

**Issue by msimberg** [LLNL/Umpire#771]
I think the check for `std::filesystem` is currently insufficient. GCC 11 updated the default C++ standard to 17. When the check is done no C++ standard flags are passed to the compilation which makes it use the default of 17 and it concludes that `std::filesystem` is available. However, the default `BLT_CXX_STD` is C++14, which makes compilation then fail because `std::filesystem` isn't available in C++14 mode.

**Comment by davidbeckingsale** [comment]
@msimberg - can you please confirm that #781 fixes this issue for you?

**Comment by evaleev** [comment]
This may be relevant: with older `libstdc++` libs may need to link against `libstdc++fs`, see https://gitlab.kitware.com/cmake/cmake/-/issues/17834 and https://github.com/vector-of-bool/CMakeCM/blob/master/modules/FindFilesystem.cmake
