### ISSUE TITLE
thread safe DynamicPool for cuda unified memory

### ISSUE THREAD

**Issue by pchong90** [LLNL/Umpire#8]
Hi,

I'm trying to use Umpire to manage CUDA unified memory. The program is multi-threaded, so I try to make a thread-safe allocator.  
Here is my code
```
auto& rm = umpire::ResourceManager::getInstance();
auto um_dynamic_pool = rm.makeAllocator<umpire::strategy::DynamicPool>(
          "UMDynamicPool", rm.getAllocator("UM"));
auto thread_safe_um_dynamic_pool =
          rm.makeAllocator<umpire::strategy::ThreadSafeAllocator>(
              "ThreadSafeUMDynamicPool", rm.getAllocator("UMDynamicPool"));
```
The `thread_safe_um_dynamic_pool` allocator is stored in a global class and used by all threads to allocate and deallocate cuda unified memory.

However, I found that my program will stochastically throw an error when deallocating unified memory when using multiple threads.
Sometimes it throws the error here https://github.com/LLNL/Umpire/blob/develop/src/umpire/util/AllocationMap.cpp#L121
sometimes here
https://github.com/LLNL/Umpire/blob/develop/src/umpire/util/AllocationMap.cpp#L75

I try to generate a nice log file by lock the `logMessage` function, but the lock hides the errors and I can't trigger the same error again. 

I attached the original log file, but the output is in a mess because of multi-threading. Sorry about the inconvenience.
[umpire_log.txt](https://github.com/LLNL/Umpire/files/2295187/umpire_log.txt)

So, am I doing the correct thing if I want to use a thread-safe dynamic pool for CUDA unified memory?
Would you take a look at this in case there is a real issue?

Thanks,

**Comment by davidbeckingsale** [comment]
That looks like it should work. Would you be able to share the reproducer?

**Comment by davidbeckingsale** [comment]
Also, could you try printing the address of the shared Allocator from each thread, just to confirm they are all sharing the same one?

**Comment by davidbeckingsale** [comment]
Okay, thank you!

**Comment by pchong90** [comment]
Hi David,

Sorry to bother you over the weekend. 
I made a simple example that only uses umpire and independent of my project code. 
The code is attached to this comment.
I compiled umpire with the following configuration
```
#!/bin/bash

UMPIRE_SOURCE=/path/to/source/Umpire

cmake \
  -DCMAKE_INSTALL_PREFIX=

/path/to/install/umpire \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_OPENMP=OFF \
  -DENABLE_CUDA=ON \
  -DENABLE_LOGGING=ON \
  -DENABLE_ASSERTS=ON \
  ${UMPIRE_SOURCE}
```
To compile the example,  rename `umpire_test.cpp.txt` to `umpire_test.cpp`, do `cmake -Dumpire_DIR=... ./` then `make`.
To run: `./umpire_test > output` This redirect the output to file so that it is easy to see the error.

I can hit the error around 1-2 times every 20 runs. Tested on Ubuntu 18.04 with GCC 7.3 and CUDA 9.1. 

sometime the error shows up as `Segmentation fault`, but most times it throws error in here https://github.com/LLNL/Umpire/blob/develop/src/umpire/util/AllocationMap.cpp#L121

Please let me know if you can reproduce the error or not. 

Thank you very much.

[umpire_test.cpp.txt](https://github.com/LLNL/Umpire/files/2299894/umpire_test.cpp.txt)
[CMakeLists.txt](https://github.com/LLNL/Umpire/files/2299897/CMakeLists.txt)

**Comment by pchong90** [comment]
Hi David,
I think I find an issue and it fixes this problem. I will send a pull request once I confirmed that it did fix the problem by doing more tests.

**Comment by davidbeckingsale** [comment]
Sounds good! Thanks very much.
