### ISSUE TITLE
fmt bleeds out of Umpire

### ISSUE THREAD

**Issue by adayton1** [LLNL/Umpire#801]
**Describe the bug**

The fmt macros need to be prefixed with UMPIRE_ to avoid conflicting with any libraries/applications using a different version of fmt. The real fix is to let consumers of Umpire point Umpire at the fmt install to use.

**Comment by davidbeckingsale** [comment]
Understood. I think we will switch to an external fmt at some point soon (ish).

**Comment by adayton1** [comment]
Closed in favor of #814
