### ISSUE TITLE
Fix c++17 support

### ISSUE THREAD

**Issue by adayton1** [LLNL/Umpire#809]
**Describe the bug**

std::random_shuffle has been removed in c++17 and should be replaced with std::shuffle:

https://github.com/LLNL/Umpire/blob/develop/benchmarks/file_resource_benchmarks.cpp#L66
https://github.com/LLNL/Umpire/blob/develop/tests/unit/resource/shared_memory_resource_tests.cpp#L214

**Comment by mcfadden8** [comment]
Hi @adayton1, I went ahead and implemented a fix for this in the PR mentioned above.  I am not sure if you had a test for this that you were trying to use, but feel free to try this out.

**Comment by adayton1** [comment]
Thanks! I didn't have a specific case (we don't build the examples in Umpire), but I encountered this when grepping the code for features that were removed in c++17.
