### ISSUE TITLE
fmt bleeds out of Umpire

### ISSUE THREAD

**Issue by adayton1** [LLNL/Umpire#814]
**Describe the bug**

The fmt functions are appropriately wrapped, but the fmt macros also need an umpire prefix to avoid conflicting with other versions of fmt (such as in axom, conduit, etc...). I changed all macros in fmt to start with UMPIRE_FMT and that fixed the issues for me. I don't have developer access to Umpire, or I would submit a fix myself. I think this should be a patch release for 2022.10 since others will probably encounter this issue if they use axom or conduit.

In the long run, rather than try to wrap fmt, it would be nice to let the user provide an external fmt (I believe that is the direction umpire and axom are heading, but wanted to double check).

**Comment by rhornung67** [comment]
Yes, we plan to pull fmt out of Axom and rely on it as a TPL in the near future.

**Comment by adayton1** [comment]
I guess I can create a merge request from my fork:
https://github.com/LLNL/Umpire/pull/815

**Comment by davidbeckingsale** [comment]
Closed by #816
