### ISSUE TITLE
Different behavior between QuickPool and DynamicPool for PercentReleasableHWM

### ISSUE THREAD

**Issue by asidhu0** [LLNL/Umpire#846]
**Describe the bug**

An observation I had for my `PercentReleasableHWM` test was that after coalescing, when I wanted to deallocate the rest of the pool (to avoid a memory leak), I had to call `release` first and then I could deallocate the rest of the memory. If I didn't call `release` then the test for `QuickPool` would result in an infinite loop where `coalesce` would keep calling `deallocate` and vice versa. However, this problem was not observed in `DynamicPool`. I think the reason why is because in `DyanmicSizePool.hpp` the `deallocate` function does not call its corresponding `coalesce` function while in `QuickPool.cpp`, `deallocate` and `coalesce` continuously call each other if certain conditions are met. This might be intended behavior because the two pools are different but I just wanted to state what I saw happening. 

**To Reproduce**

Run the `PercentReleasableHWM` test in `pool_heuristics_test.cpp` but comment out line 123 where it says `ASSERT_NO_THROW(a.first.release());`. The commented out version will work for DynamicPool but not for QuickPool. 

**Expected behavior**

The behaviors of DynamicPool and QuickPool should mirror each other. So if I need to release after coalescing to further deallocate memory from the pool, this behavior should be observed in both pools, not just QuickPool. 

**Compilers & Libraries (please complete the following information):**

Using Umpire 2023.06.0 and GCC 8.3.1

**Additional context**

This inconsistency was found when writing a test for `PercentReleasableHWM` for my `Fixed coalescing call for blocks releasable heuristic #831` branch.

**Comment by kab163** [comment]
Resolved with PR #831
