### ISSUE TITLE
Integer overflow on allocations > 2GB in Fortran

### ISSUE THREAD

**Issue by aaroncblack** [LLNL/Umpire#849]
Umpire gets an overflow when trying to allocate > 2GB using the Fortran bindings.

The current Fortran bindings in Umpire allocations make use of a 'product' calculation to determine the total size of a shaped array coming in from Fortran.  For very large arrays, this can cause an overflow of the integer temporary coming out of Product.

I have some example code below, based on the code in the Umpire allocate calls in the Fortran interface.  I have an example variable of 9GB I want to allocate, within a 3d double array.

```
program fmain
   use iso_c_binding
   implicit none

   integer, dimension(3) :: dims
   real(C_DOUBLE), dimension(3) :: array
   type(C_PTR) :: data_ptr

   real(C_DOUBLE) :: size_type
   integer(C_SIZE_T) :: num_bytes, i
   integer(C_SIZE_T) :: the_product
   integer(C_SIZE_T) :: the_size_of

   dims(1) = 1024
   dims(2) = 9600
   dims(3) = 120

   print *, "Array shape: ", SHAPE(dims)
   print *, "Array dims are", dims
   print *, "Size of var type is ", sizeof(size_type)
   print *, "Number of total bytes should be 9,437,184,000 (close to 9GB)"

!  Algorithm in UMPIRE binding:
!  Gets overflows due to the signed integer temporaries.
   num_bytes = product(dims) * sizeof(size_type)
   print *, "Number of bytes ( using product and sizeof multiplication ) is: ", num_bytes
   print *, "Number of GB is: ", num_bytes / 1024 / 1024 / 1024

!  Suggested fix is to break out the product into a loop.
   the_product = 1.0
   do i=1,SIZE(array)
      the_product = the_product * dims(i)
   enddo

   the_size_of = sizeof(size_type)
   num_bytes = the_product * the_size_of

   print *, "Number of bytes ( using split out operation with size_t vars ) is: ", num_bytes
   print *, "Number of GB is: ", num_bytes / 1024 / 1024 / 1024
end program fmain
```

I used to have this issue in the UMT code when I had bindings around CUDA C allocation calls.  In fact, it might be possible that this Umpire code for the wrapped allocations may have come from some early examples from me and I forgot to notify you when I later had to fix my code... whoops.

**Comment by davidbeckingsale** [comment]
Fixed by #851
