### ISSUE TITLE
Wrong usage of the -fcompare-debug-second gcc flag

### ISSUE THREAD

**Issue by rasolca** [LLNL/Umpire#852]
**Describe the bug**

The flag `-fcompare-debug-second` added on https://github.com/LLNL/Umpire/blob/20839b2e8e8972070dd8f75c7f00d50d6c399716/src/tpl/CMakeLists.txt#L199
prevent correct execution of coverage tests.

**To Reproduce**

compile a cmake project which link to Umpire with flags `-fprofile-arcs -test-coverage` and notice the absence of `.gcno` files.

**Expected behavior**

The flag `-fcompare-debug-second` should not be propagated to dependent cmake projects which link to Umpire.

**Compilers & Libraries (please complete the following information):**
 - Compiler: any GCC version 

**Additional context**

According to gcc documentation:
```
-fcompare-debug-second

    This option is implicitly passed to the compiler for the second compilation requested by -fcompare-debug, along with options to silence warnings, and omitting other options that would cause the compiler to produce output to files or to standard output as a side effect. Dump files and preserved temporary files are renamed so as to contain the .gk additional extension during the second compilation, to avoid overwriting those generated by the first.

    When this option is passed to the compiler driver, it causes the first compilation to be skipped, which makes it useful for little other than debugging the compiler proper.
```

It is not clear why this option is added in Umpire as `-fcompare-debug` is not used.
Anyway the important part of the doc is `omitting other options that would cause the compiler to produce output to files` as `.gcno` files needed by coverage are suppressed as well.

**Comment by kab163** [comment]
Using gcc/8.3.1 and cmake/3.20.2 with the `-fprofile-arcs -ftest-coverage` flags, I could not reproduce this on Lassen. However, removing that flag from the tpl/CMakeLists.txt didn't break anything either and all tests still pass. PR opened for this.
