### ISSUE TITLE
Avoiding hardcoded install paths (e.g. `lib` vs `lib64`)

### ISSUE THREAD

**Issue by wavefunction91** [LLNL/Umpire#855]
**Is your feature request related to a problem? Please describe.**

Currently, `Umpire` hardcodes the subpaths of install targets (e.g. `lib`). In a vacuum this may or may not be problematic, but when pulled in as a dependency, the inability to change these types of paths can be problematic (see e.g. https://github.com/ValeevGroup/tiledarray/issues/428, where the locally defined `LIBDIR` may clash with the install location of `Umpire` if not careful)

**Describe the solution you'd like**

It would be desirable for `Umpire` to at least respect `CMAKE_INSTALL_LIBDIR` to allow for consistent install locations when pulled in as a dependency. Typically we set this via `GNUInstallDirs.cmake`,  but that's less of a concern if at least the behavior is overridable via the aforementioned variable. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by davidbeckingsale** [comment]
Thank you for the report, working on it!
