### ISSUE TITLE
Error (probably escalated warning) in fmt 10.2.1 when building with IBM clang 14.0.5

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/Umpire#877]
**Describe the bug**

This is likely an escalated warning (due to -Werror), only seen with IBM clang.

```console
/dev/shm/lassen228-1750856/clang-14.0.5.ibm.gcc.8.3.1/fmt-10.2.1-xt4zmnqcvwuumhy3zsqldfuh3cxhb35k/include/fmt/format.h(1335): error: variable "buffer" may not be initialized
```

**To Reproduce**

```console
working_dir="/usr/workspace/${USER}/Umpire/1750856-$(date +%s)" 
mkdir -p ${working_dir} && cd ${working_dir} 
git clone https://github.com/LLNL/Umpire.git --single-branch --depth=1 
cd Umpire 
git fetch origin --depth=1 32494352f6d07ae838e61083ecfdf2608d39b96b 
git checkout 32494352f6d07ae838e61083ecfdf2608d39b96b 
git submodule update --init --recursive 

export MODULE_LIST=""
export SPEC="~shared +fortran +tools tests=basic  +cuda %clang@=14.0.5.ibm.gcc.8.3.1 ^cuda@10.1.243+allow-unsupported-compilers "
export USE_DEV_SHM="false"

lalloc 1 -W 10 -q pci ./scripts/gitlab/build_and_test.sh
```

**Expected behavior**

A clear and concise description of what you expected to happen:

**Compilers & Libraries (please complete the following information):**
 - Compiler & version: IBM Clang 14.0.5 with gcc 8.3.1 toolchain: 
 - CUDA version (if applicable): 10.1.243 

**Additional context**

Happening in CI in a new branch updating compiler specs

**Comment by davidbeckingsale** [comment]
@adrienbernede it should be addressed by this patch: https://github.com/LLNL/radiuss-spack-configs/blob/main/packages/fmt/fmt-no-variable-initialize_10.0.0.patch but doesn't look like it's getting applied for IBM Clang 14.0.5: https://github.com/LLNL/radiuss-spack-configs/blob/main/packages/fmt/package.py#L97

**Comment by adrienbernede** [comment]
Great catch, thanks!

**Comment by adrienbernede** [comment]
It worked!
