### ISSUE TITLE
`-Mfree` is not correct for all LLVM Fortran compilers

### ISSUE THREAD

**Issue by bcornille** [LLNL/Umpire#890]
**Describe the bug**

When compiling Umpire with the LLVM flang compiler (flang-new), Umpire sets `-Mfree` as the flag for free form Fortran. That flag is for the classic-flang compiler and the correct flag is `-ffree` for LLVM flang.

**To Reproduce**

Compile Umpire with flang-new.

The `-ffree` flag should be set when compiling Fortran source. 

**Compilers & Libraries (please complete the following information):**
```
>> flang-new --version
flang-new version 19.0.0git (https://github.com/ROCm/llvm-project d5a3c4dc3bb96d345db1f7c63d5e3e5ba273af8c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /share/contrib-modules/Core/amd-trunk-dev/2024-07-09_18.0-0/bin
Build config: +assertions
Configuration file: /share/contrib-modules/Core/amd-trunk-dev/2024-07-09_18.0-0/bin/flang.cfg
```
Any build of flang-new should expose this issue.

**Additional context**

I would recommend using the CMake property [Fortran_FORMAT](https://cmake.org/cmake/help/latest/prop_tgt/Fortran_FORMAT.html) since recent CMake versions are aware of the LLVMflang compiler. If this does not work with the minimum CMake version then logic should be included to disambiguate LLVM flang from classic-flang. `Fortran_COMPILER_FAMILY_IS_CLANG` will be true in both cases.

**Comment by davidbeckingsale** [comment]
@bcornille do you know the specific CMake version where the correct flag is used for both LLVM flang and classic flang?

**Comment by bcornille** [comment]
I don't know offhand. I'll have to do some testing or maybe git blame in the cmake repo to see if I can determine that.

**Comment by bcornille** [comment]
Support for LLVMFlang was added in CMake 3.24. ~~As far as I can tell the format flag for classic flang has never been correct.~~ You can change the condition to use CMAKE_Fortran_COMPILER_ID, which is Flang for classic flang and LLVMFlang for flang-new.

**Comment by bcornille** [comment]
The classic flang repo says the flag is `-Mfreeform`, the PGI compiler that it was based off of was `-Mfree`, and the AOCC compiler documentation shows `-ffree-form`. So I don't know if it accepts multiple of these and if it's even consistent across the flavors that will all identify as Flang.

CMake sets it to use `-ffree-form`. Is there a specific flavor of classic flang that Umpire should support?

**Comment by bcornille** [comment]
The ROCm Fortran compiler (`amdflang` flavor of classic flang) accepts all three flags, so if that is true of the other classic flang flavors then CMake 3.24 should be sufficient to always use `Fortran_FORMAT`.

**Comment by davidbeckingsale** [comment]
thanks @bcornille - I was seeing failures in our internal CI with CMake 3.24 and the changes I have in #891 

Would the check on `CMAKE_Fortran_COMPILER_ID` solve the issue for you?

**Comment by bcornille** [comment]
Yes it would.
